[package]
name = "background-jobs"
description = "Background Jobs implemented with tokio and futures"
version = "0.2.0"
license = "GPL-3.0"
authors = ["asonix <asonix@asonix.dog>"]
repository = "https://git.asonix.dog/asonix/background-jobs"
readme = "README.md"
keywords = ["jobs", "processor"]
edition = "2018"

[workspace]
members = [
    "jobs-core",
    "jobs-server",
    "examples/server-jobs-example",
]

[features]
default = ["background-jobs-server", "background-jobs-server/tokio-zmq"]

[dependencies.background-jobs-core]
version = "0.2"
path = "jobs-core"

[dependencies.background-jobs-server]
version = "0.2"
path = "jobs-server"
optional = true
