[package]
name = "background-jobs"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]
edition = "2018"

[workspace]
members = [
    "jobs-actix",
    "jobs-core",
    "jobs-server-tokio",
    "jobs-tokio",
    "examples/actix-jobs-example",
    "examples/server-jobs-example",
    "examples/tokio-jobs-example",
]

[features]
default = ["jobs-actix", "jobs-server-tokio", "jobs-server-tokio/tokio-zmq", "jobs-tokio"]

[dependencies.jobs-actix]
version = "0.1"
path = "jobs-actix"
optional = true

[dependencies.jobs-core]
version = "0.1"
path = "jobs-core"

[dependencies.jobs-server-tokio]
version = "0.1"
path = "jobs-server-tokio"
optional = true

[dependencies.jobs-tokio]
version = "0.1"
path = "jobs-tokio"
optional = true
