[package]
name = "background-jobs"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]
edition = "2018"

[workspace]
members = [
    "jobs-core",
    "jobs-server",
    "examples/server-jobs-example",
]

[features]
default = ["background-jobs-server", "background-jobs-server/tokio-zmq"]

[dependencies.background-jobs-core]
version = "0.1"
path = "jobs-core"

[dependencies.background-jobs-server]
version = "0.1"
path = "jobs-server"
optional = true
