[package]
name = "background-jobs"
description = "Background Jobs implemented with tokio and futures"
version = "0.4.0"
license = "GPL-3.0"
authors = ["asonix <asonix@asonix.dog>"]
repository = "https://git.asonix.dog/asonix/background-jobs"
readme = "README.md"
keywords = ["jobs", "processor"]
edition = "2018"

[workspace]
members = [
    "jobs-actix",
    "jobs-core",
    "jobs-server",
    "examples/server-jobs-example",
]

[features]
default = ["background-jobs-server", "background-jobs-server/tokio-zmq"]
no_unix = ["background-jobs-server", "background-jobs-server/futures-zmq"]
actix = ["background-jobs-actix"]

[dependencies.background-jobs-core]
version = "0.4"
path = "jobs-core"

[dependencies.background-jobs-server]
version = "0.4"
path = "jobs-server"
default-features = false
optional = true

[dependencies.background-jobs-actix]
version = "0.4"
path = "jobs-actix"
optional = true
