[package]
name = "background-jobs"
description = "Background Jobs implemented with tokio and futures"
version = "0.5.0"
license = "GPL-3.0"
authors = ["asonix <asonix@asonix.dog>"]
repository = "https://git.asonix.dog/asonix/background-jobs"
readme = "README.md"
keywords = ["jobs", "processor"]
edition = "2018"

[workspace]
members = [
    "jobs-actix",
    "jobs-core",
]

[features]
default = ["background-jobs-actix"]

[dependencies.background-jobs-core]
version = "0.4"
path = "jobs-core"

[dependencies.background-jobs-actix]
version = "0.5"
path = "jobs-actix"
optional = true
