[package]
name = "jobs"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]

[dependencies]
failure = "0.1"
futures = "0.1.21"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
