[package]
name = "jobs"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]
edition = "2018"

[workspace]
members = [
    "jobs-core",
    "jobs-executor",
    "jobs-tokio",
    "examples/process-jobs",
]

[features]
default = ["jobs-tokio"]

[dependencies.jobs-core]
version = "0.1"
path = "jobs-core"

[dependencies.jobs-executor]
version = "0.1"
path = "jobs-executor"
optional = true

[dependencies.jobs-tokio]
version = "0.1"
path = "jobs-tokio"
optional = true
