[package]
name = "background-jobs-tokio"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]
edition = "2018"

[dependencies]
futures = "0.1"
log = "0.4"
tokio = "0.1"
tokio-threadpool = "0.1"

[dependencies.background-jobs-core]
version = "0.1"
path = "../jobs-core"
