[package]
name = "jobs-core"
version = "0.1.0"
authors = ["asonix <asonix@asonix.dog>"]
edition = "2018"

[dependencies]
failure = "0.1"
futures = "0.1.21"
log = "0.4"
kv = "0.6"
lmdb = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
